name: Deploy QA to EC2

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22

          script: |
            set -e

            echo "Starting QA deployment..."

            cd /home/ubuntu/help

            git checkout qa
            git pull --ff-only origin qa

            docker compose up -d --build --remove-orphans

            echo "Running containers:"
            docker ps

            echo "QA deployment completed."
